config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

 devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  namespace :public do
    get 'cart_items/index'
  end
  namespace :public do
    get 'orders/new'
    get 'orders/confirm'
    get 'orders/complete'
    get 'orders/index'
    get 'orders/show'
  end
  namespace :public do

    resources:items, only:[:index, :show]
  end

  namespace :public do
    resources:addresses, only:[:new, :index, :edit, :create, :update, :destroy]
  end
  namespace :public do
   resources :customers, only: [:show, :edit, :update]
   get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
  end
  namespace :public do
    get 'homes/top'
    get 'homes/about'
  end

  namespace :admin do
    get 'orders/show'
  end
  namespace :admin do
    resources:customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :items, only: [:new, :index, :create, :edit, :show, :update]
  end

  namespace :admin do
    resources :genres, only: [:new, :index, :create, :edit, :update]
  end

  namespace :admin do
     get 'homes/top'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    def get_image
      unless image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpg')
        image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      image
    end
    
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/controllers/admins/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer.id)
  end

  def unsubscribe
    @user = User.find(params[:id])
  # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end
  
   private
  # ストロングパラメータ
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
  def after_sign_in_path_for(resource)
    public_homes_top_path
  end
  def after_sign_up_path_for(resource)
    public_homes_top_path
  end

  def after_sign_out_path_for(resource)
    public_homes_about_path
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
  <div class="container">
    <div class="row my-3">
      <div class="col-sm-8 px-sm-0 offset-sm-1">
        <h2><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
      </div>
    </div>
    <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>

      <div class="row">
        <div class="col-2 offset-md-1"><%= f.label "氏名" %></div>
        <div class="col-2"><%= f.text_field :last_name, :size => "10" %></div>
        <div class="col-3"><%= f.text_field :first_name, :size => "10" %></div>
      </div>
      
      <div class="row">
        <div class="col-2 offset-md-1"><%= f.label "フリガナ" %></div>
        <div class="col-2"><%= f.text_field :last_name_kana, :size => "10" %></div>
        <div class="col-3"><%= f.text_field :first_name_kana, :size => "10" %></div>
      </div>
      
      <div class="row">
        <div class="col-3 offset-md-1"><%= f.label "メールアドレス" %></div>
        <div class="col-3"><%= f.email_field :email, :size => "25"%></div>
      </div>
      
      <div class="row">
        <div class="col-3 offset-md-1"><%= f.label "郵便番号" %></div>
        <div class="col-3"><%= f.text_field :postal_code, :size => "10" %></div>
      </div>
      
      <div class="row">
        <div class="col-3 offset-md-1"><%= f.label "住所" %></div>
        <div class="col-3"><%= f.text_field :address, :size => "40" %></div>
      </div>
      
      <div class="row">
        <div class="col-3 offset-md-1"><%= f.label "電話番号" %></div>
        <div class="col-3"><%= f.text_field :telephone_number %></div>
      </div>
      
      <div class="row">
        <div class="col-3 offset-md-1"><%= f.label "会員ステータス" %></div>
        <div class="col-3"><%= f.radio_button :is_deleted, :false %>
          <%= f.label :withdrawal_status, "有効" %>
          <%= f.radio_button :is_deleted, :true %>
          <%= f.label :withdrawal_status, "退会" %>
        </div>
      </div>
      
      <div class="row mb-2">
        <div class="col-lg-6 px-sm-0 offset-sm-1">
          <%= f.submit "変更を保存" %>
        </div>
      </div>
    <% end %>
  </div>

app/views/admin/customers/index.html.erb
  <div class="container">
    <div class="row my-3">
      <div class="col-sm-8 px-sm-0 offset-sm-1">
        <h1>会員一覧</h1>
      </div>
    </div>
    <div class="row my-3">
      <div class="col-sm-10 px-sm-0 offset-sm-1">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th class="table-active">会員ID</th>
              <th class="table-active">氏名</th>
              <th class="table-active">メールアドレス</th>
              <th class="table-active">ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
              <tr>
                <td><%= customer.id %></td>
                <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %></u></td>
                <td><%= customer.email %></td>
                <td><% if customer.is_deleted == false %>
                <p>有効</p>
                <% else %>
                <p>退会</p>
                <% end %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/admin/customers/show.html.erb
  <div class="container">
    <div class="row my-3">
      <div class="col-sm-8 px-sm-0 offset-sm-1">
        <h2><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6 px-sm-0 offset-sm-1">
        <table class="table table-bordered">
          <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
          </tr>

          <tr>
            <th>氏名</th>
            <td><%= @customer.last_name + @customer.first_name %></td>
          </tr>

          <tr>
            <th>カナ</th>
            <td><%= @customer.last_name_kana + @customer.first_name_kana %></td>
          </tr>

          <tr>
            <th>郵便番号</th>
            <td><%= @customer.postal_code %></td>
          </tr>

           <tr>
            <th>住所</th>
            <td><%= @customer.address %></td>
          </tr>

          <tr>
            <th>電話番号</th>
            <td><%= @customer.telephone_number %></td>
          </tr>

          <tr>
            <th>メールアドレス</th>
            <td><%= @customer.email %></td>
          </tr>

          <tr>
            <th>会員ステータス</th>
            <td><% if @customer.is_deleted == false %></td>
            <td>有効</td>
            <% else %>
            <td>退会<td>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-lg-6 px-sm-0 offset-sm-1">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id) %>
      <%= link_to "注文履歴一覧を見る", admin_homes_top_path %>
    </div>
  </div>