config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

 devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  namespace :public do
    get 'cart_items/index'
  end
  namespace :public do
    get 'orders/new'
    get 'orders/confirm'
    get 'orders/complete'
    get 'orders/index'
    get 'orders/show'
  end
  namespace :public do

    resources:items, only:[:index, :show]
  end

  namespace :public do
    resources:addresses, only:[:new, :index, :edit, :create, :update, :destroy]
  end
  namespace :public do
   resources :customers, only: [:show, :edit, :update]
   get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
  end
  namespace :public do
    get 'homes/top'
    get 'homes/about'
  end

  namespace :admin do
    get 'orders/show'
  end
  namespace :admin do
    resources:customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :items, only: [:new, :index, :create, :edit, :show, :update]
  end

  namespace :admin do
    resources :genres, only: [:new, :index, :create, :edit, :update]
  end

  namespace :admin do
     get 'homes/top'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    def get_image
      unless image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpg')
        image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      image
    end
    
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre, optional: true
  enum sales_status: { on_sale: 0, draft: 1 }
  has_many :cart_items, dependent: :destroy
  
  # 消費税を加えた商品価格
    def add_tax_price
        (self.price * 1.10).round
    end
end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/controllers/admins/genres_controller.rb
class Admin::GenresController < ApplicationController

    def index
    @genre = Genre.new
    @genres = Genre.all

    end
  def create
    @genre = Genre.new(genre_params)
    @genre.save!
    redirect_to '/admin/genres'
  end

  def edit
    @genre = Genre.find(params[:id])

  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private # ストロングパラメータ

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admins/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @customers = Customer.all
  end

  
end

app/controllers/admins/items_controller.rb
class Admin::ItemsController < ApplicationController


  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    item = Item.new(item_params)
    item.save!
    redirect_to '/admin/items'
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @genres = Genre.all
  end


  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(params[:id])#item.id
  end

   private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image, :sales_status)#index_items_on_genre_id
  end
end

app/controllers/admins/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @orders = Order.all
     @order_details = OrderDetail.where(order_id: @order)
      @production_status = @order.order_details.pluck(:production_status)
  end
  
  def update 
     @order = Order.find(params[:id])
     redirect_to admin_order_path(@order)
  end 
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
    
  def after_sign_in_path_for(resource)
    public_homes_top_path
  end
  def after_sign_up_path_for(resource)
    public_homes_top_path
  end

  def after_sign_out_path_for(resource)
    public_homes_top_path
  end
  # before
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>NaganoCake2</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>

    <body>
      <header>
        <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
         <!--adminログイン時のヘッダー-->
              <% if admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "商品一覧", admin_items_path do %> <%#アイコンを付けるかもしれないからdoを付けておく%>
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to "会員一覧", admin_customers_path do %>
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to "注文履歴一覧", admin_homes_top_path  do %>
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to "ジャンル一覧", admin_genres_path do%>
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete do %>
                  <% end %>
                </li>

                <% elsif customer_signed_in? %><!--customersログイン時のヘッダー-->
                  <li class="nav-item">
                  ようこそ <%= link_to customer_session_path do %>
                    <strong><%= current_customer.last_name %></strong>
                  <% end %>
                   さん
                  </li>

                  <li class="nav-item">
                    <%= link_to public_homes_top_path do %>
                      <i class="fas fa-user-circle">マイページ</i>
                    <% end %>
                  </li>

                  <li class="nav-item">
                    <%= link_to  public_items_path do %>
                      <i class="fas fa-cookie-bite">商品一覧</i>
                    <% end %>
                  </li>

                  <li class="nav-item">
                    <%= link_to public_cart_items_index_path do %>
                      <i class="fas fa-shopping-cart">カート</i>
                    <% end %>
                  </li>

                  <li class="nav-item">
                    <%= link_to destroy_customer_session_path, method: :delete do %>
                      <i class="fas fa-sign-out-alt">ログアウト</i>
                    <% end %>
                  </li>

                <% else %>
                    <!--ログイン前時のヘッダー-->
                  <li class="nav-item">
                    <%= link_to public_homes_about_path do %>
                      <i class="fas fa-store-alt">About</i>
                    <% end %>
                  </li>

                  <li class="nav-item">
                    <%= link_to public_items_path do %>
                      <i class="fas fa-cookie-bite">商品一覧</i>
                    <% end %>
                  </li>

                  <li class="nav-item">
                    <%= link_to new_customer_registration_path do %>
                      <i class="fas fa-user-plus">新規登録</i>
                    <% end %>
                  </li>

                  <li class="nav-item">
                    <%= link_to new_customer_session_path do%>
                      <i class="fas fa-user">ログイン</i>
                    <% end %>
                  </li>
                <% end %>
      </header>
      <main>
        <%= yield %>
      </main>

    </body>
  </html>